<?php
declare(strict_types=1);

namespace Tests\JeckelLab\CommandDispatcher\Resolver;

use JeckelLab\CommandDispatcher\CommandHandler\CommandHandlerInterface;
use JeckelLab\CommandDispatcher\Command\CommandInterface;
use JeckelLab\CommandDispatcher\Resolver\CommandHandlerResolver;
use JeckelLab\CommandDispatcher\Resolver\HandlerNotFoundException;
use PHPUnit\Framework\TestCase;
use Psr\Container\ContainerInterface;

/**
 * Class CommandHandlerResolverTest
 */
final class CommandHandlerResolverTest extends TestCase
{
    /**
     * @var CommandHandlerResolver
     */
    protected $resolver;

    /**
     * setup
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->resolver = new CommandHandlerResolver();
    }

    /**
     * @test resolve
     */
    public function testResolveWithNoHandlers(): void
    {
        $this->expectException(HandlerNotFoundException::class);

        $this->resolver->resolve($this->createMock(CommandInterface::class));
    }

    /**
     * Test resolve without container
     */
    public function testResolveWithoutContainer(): void
    {
        $command = $this->createMock(CommandInterface::class);
        $handler = $this->createMock(CommandHandlerInterface::class);

        $this->assertSame($this->resolver, $this->resolver->registerHandler($handler, [get_class($command)]));
        $this->assertSame($handler, $this->resolver->resolve($command));
    }

    public function testResolveWithContainer(): void
    {
        $handlerName = 'command.handler';

        $command = $this->createMock(CommandInterface::class);
        $handler = $this->createMock(CommandHandlerInterface::class);
        $container = $this->createMock(ContainerInterface::class);
        $container->expects($this->once())
            ->method('has')
            ->with($handlerName)
            ->willReturn(true);
        $container->expects($this->once())
            ->method('get')
            ->with($handlerName)
            ->willReturn($handler);

        $resolver = new CommandHandlerResolver($container);
        $this->assertSame($resolver, $resolver->registerHandlerService($handlerName, [get_class($command)]));
        $this->assertSame($handler, $resolver->resolve($command));
    }
}
